name: Hello World
on: workflow_dispatch
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, World!"
  say_world:
    runs-on: ubuntu-latest
    steps:
      - name: Say World
        run: ./world.sh