name: Hello World
on: [push,workflow_dispatch]
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: say Hello
        run: echo "Hello, World!"
  hello_world_script_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Make it Executable
        run: chmod +x ./world.sh
      - name: Run Hello World
        run: ./world.sh